### ISSUE TITLE
Removing all files from options, will appear after clicking apply again

### ISSUE THREAD

**Issue by Chris2011** [Chris2011/readmeinprojectview#15]
When I select all files, removed them and hit apply, they appear again in the list, which is not expected. Maybe @skyghis you can have a look if you want? Smth unexpected happens there :).

**Comment by skyghis** [comment]
It is an expected behaviour : [DisplayReadmeFilesPanel(112)](https://github.com/Chris2011/readmeinprojectview/blob/95a7c9844f369750dc4703b6a19a20d735c766df/src/main/java/de/markiewb/netbeans/plugins/readmeinprojectview/DisplayReadmeFilesPanel.java#L112)

The goal was to have a way to reset the values to the defaults.

What behaviour do you expect when no file is set ?

**Comment by Chris2011** [comment]
Ok, I understand, maybe you can add a default button? NetBenas does this in the Misc -> Files panel for excluding files for indexing. You can remove everythng, which makes the field empty and you can click on default and set the default back.

**Comment by Chris2011** [comment]
If no file is set, the field should be empty.

**Comment by skyghis** [comment]
So "empty text box" = "no file to display" ?

I don't see any use case but it should be possible to do it quite easily.
